#!/bin/bash

helpFunction(){
    echo "Usage: $0 -i <Video location>"
    echo -e "\t-i Input video location"
    echo -e "\t-o (Optional) Output video name"
    echo -e "\t-f (Optional) Format"
    echo ""
    exit 1
}

while getopts "hd:h:i:o:f:" opt
do
    case "$opt" in
        h ) helpFunction ;;
        i ) input="$OPTARG" ;;
        o ) output="$OPTARG" ;;
        f ) format="$OPTARG" ;;
        ? ) helpFunction ;;
    esac
done

if [ -z "$input" ]
then
    helpFunction
fi

if [ "$format" == "mov"] || [ -z "$format" ]
then
    ffmpeg -i "$PWD/$input" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov "$PWD/${output:=${input%.*}-(encoded)}.mov"
else
    ffmpeg -i "$PWD/$input" -c:v libx264 -crf 22 -pix_fmt yuv420p -b:a 128k -f "$format" "$PWD/${output:=${input%.*}-(encoded)}.${format}"
fi